#!/bin/bash
# Script to integrate lesson plan generator into server.js

echo "To integrate the lesson plan generator into your QLA Mathematics Platform:"
echo ""
echo "1. Add these require statements at the top of server.js (after other route imports):"
echo ""
echo "const lessonPlanGeneratorRouter = require('./routes/lesson-plan-generator');"
echo "const lessonPlanExportRouter = require('./routes/lesson-plan-export');"
echo ""
echo "2. Add these route registrations in server.js (after other API routes):"
echo ""
echo "// Lesson Plan Generator Routes"
echo "app.use('/api/lesson-plan-generator', requireAuth, requireTeacher, lessonPlanGeneratorRouter);"
echo "app.use('/api/lesson-plan-export', requireAuth, requireTeacher, lessonPlanExportRouter);"
echo ""
echo "3. Install the required dependency for Word document generation:"
echo ""
echo "npm install docx"
echo ""
echo "4. Replace your existing portal-teacher.html with portal-teacher-enhanced.html"
echo ""
echo "5. Run the migration to create the necessary database tables:"
echo ""
echo "node scripts/run-migrations.js"
echo ""
echo "The lesson plan generator will then be available in the Teacher Portal!"
