-- 010_seed_skills_gr7_gr8.sql
BEGIN;
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Number System Overview (Rational & Irrational)", "", 7, 1, 1);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Prime Factorization Toolkit (Factors/Multiples, HCF/LCM)", "", 7, 1, 2);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Compare & Simplify Rational Numbers", "", 7, 1, 3);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Add/Subtract Rational Numbers", "", 7, 1, 4);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Multiply/Divide Rational Numbers", "", 7, 1, 5);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Absolute Value", "", 7, 1, 6);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Applications & Word Problems with Rationals", "", 7, 1, 7);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Order of Operations (BEDMAS) with Rationals", "", 7, 1, 8);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Write Algebraic Expressions", "", 7, 3, 1);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Collect Like Terms", "", 7, 3, 2);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Algebraic Products", "", 7, 3, 3);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Evaluate Algebraic Expressions", "", 7, 3, 4);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Expand Brackets", "", 7, 3, 5);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Factorize Linear Expressions", "", 7, 3, 6);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Solve One\u2011step Linear Equations", "", 7, 4, 1);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Solve Two\u2011step Linear Equations", "", 7, 4, 2);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Solve Multi\u2011step Linear Equations", "", 7, 4, 3);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Express Ratios; Ratios as Fractions", "", 7, 5, 1);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Simplify & Equivalent Ratios", "", 7, 5, 2);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Problem Solving with Ratios", "", 7, 5, 3);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Use Ratios to Divide Quantities", "", 7, 5, 4);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Plot Positive & Negative Coordinates", "", 7, 7, 1);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Plot Points from a Table of Values", "", 7, 7, 2);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Graph Straight Lines", "", 7, 7, 3);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Draw Linear Graphs", "", 7, 7, 4);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Horizontal & Vertical Lines", "", 7, 7, 5);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Graph Using X & Y Intercepts", "", 7, 7, 6);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Tally & Frequency Tables", "", 7, 8, 1);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Grouping Data", "", 7, 8, 2);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Read Bar Charts", "", 7, 8, 3);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Draw Bar Charts", "", 7, 8, 4);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Stem & Leaf Plots", "", 7, 8, 5);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Mode, Mean, Median, Range", "", 7, 8, 6);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Mean from a Frequency Table", "", 7, 8, 7);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Describe Probability", "", 7, 9, 1);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Assign Probability Numbers", "", 7, 9, 2);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Sample Space", "", 7, 9, 3);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Compound Events", "", 7, 9, 4);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Probability Trees", "", 7, 9, 5);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Theoretical Probability", "", 7, 9, 6);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Complementary Events", "", 7, 9, 7);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Review: BEDMAS & Absolute Value", "", 8, 1, 1);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Convert Recurring Decimals", "", 8, 1, 2);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Round Numbers", "", 8, 1, 3);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Squares & Square Roots", "", 8, 1, 4);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Operations on Fractions", "", 8, 1, 5);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Angle Relationships (Supp/Comp/Vertical/Adjacent)", "", 8, 2, 1);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Angles in Triangles", "", 8, 2, 2);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Isosceles Triangle Properties", "", 8, 2, 3);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Angles in Quadrilaterals", "", 8, 2, 4);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Algebraic Equations in Geometry", "", 8, 2, 5);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Parallel Lines: Angle Facts", "", 8, 2, 6);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Angles in Polygons (Sum, Interior & Exterior)", "", 8, 2, 7);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Translations", "", 8, 3, 1);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Rotations", "", 8, 3, 2);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Reflections", "", 8, 3, 3);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Enlargements (Dilations)", "", 8, 3, 4);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Pie Charts", "", 8, 4, 1);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Histograms", "", 8, 4, 2);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Pythagoras: Find Hypotenuse", "", 8, 5, 1);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Pythagoras: Find a Missing Side", "", 8, 5, 2);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Converse of Pythagoras", "", 8, 5, 3);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Problem Solving with Pythagoras", "", 8, 5, 4);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Solve Two/Three\u2011step Equations (Review)", "", 8, 6, 1);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Systems by Elimination", "", 8, 6, 2);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Systems by Equating", "", 8, 6, 3);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Systems by Substitution", "", 8, 6, 4);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Convert Metric Units", "", 8, 7, 1);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Parts of a Circle", "", 8, 7, 2);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Circumference & Area of a Circle", "", 8, 7, 3);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Perimeter of Polygons", "", 8, 7, 4);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Areas: Rectangle/Triangle/Parallelogram/Trapezium", "", 8, 7, 5);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Area of Composite Shapes", "", 8, 7, 6);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Volume of Cuboids", "", 8, 7, 7);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Volume of Prisms", "", 8, 7, 8);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Volume of Cylinders", "", 8, 7, 9);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Simple Probability (with replacement)", "", 8, 8, 1);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Simple Probability (without replacement)", "", 8, 8, 2);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Construct Triangle: ASA", "", 8, 9, 1);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Construct Triangle: SAS", "", 8, 9, 2);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Construct Triangle: SSS", "", 8, 9, 3);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Interchange Number Forms", "", 8, 10, 1);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Decimals \u2192 Percentages", "", 8, 10, 2);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("One Quantity as % of Another", "", 8, 10, 3);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Percentage Increase/Decrease", "", 8, 10, 4);
INSERT INTO skills (name, description, grade, unit, order_index) VALUES ("Percentage Change", "", 8, 10, 5);

-- Create a default practice bank for each inserted skill
INSERT INTO practice_banks (skill_id, title, difficulty, created_by, is_active)
SELECT s.id, s.name || ' — Default Bank', 'medium', 'system', TRUE
FROM skills s
WHERE NOT EXISTS (SELECT 1 FROM practice_banks pb WHERE pb.skill_id = s.id);

COMMIT;
